version: "3.8"

services:
  mysql:
    image: mysql:8
    container_name: mysql_container123
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: preet
      MYSQL_DATABASE: todo_db
    ports:
      - "3307:3306"  
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  

  backend:
    build: .
    container_name: node_crud_api
    restart: always
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=preet
      - DB_NAME=todo_db
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: ["npm", "run", "start"]

volumes:
  mysql_data:
